openapi: 3.0.3
info:
  version: 0.0.1
  title: Llorería
  description: API para enviar insultos
  termsOfService: http://swagger.io/terms/
servers:
- url: http://localhost:3000/

components:
  schemas: